"""添加机构标准化字段

Revision ID: 3ccb3ece839c
Revises: ad90556f2ce8
Create Date: 2025-07-31 13:36:12.706599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ccb3ece839c'
down_revision: Union[str, Sequence[str], None] = 'ad90556f2ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('affiliation', sa.Column('normalized_name', sa.Text(), nullable=True, comment='标准化后的机构名称'))
    op.add_column('affiliation', sa.Column('postal_code', sa.String(length=20), nullable=True, comment='邮政编码'))
    op.create_index(op.f('ix_affiliation_normalized_name'), 'affiliation', ['normalized_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliation_normalized_name'), table_name='affiliation')
    op.drop_column('affiliation', 'postal_code')
    op.drop_column('affiliation', 'normalized_name')
    # ### end Alembic commands ###
