"""初始化数据库

Revision ID: ad90556f2ce8
Revises: 
Create Date: 2025-07-31 11:31:57.571277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad90556f2ce8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('affiliation', sa.Text(), nullable=False, comment='完整机构信息'),
    sa.Column('department', sa.String(length=300), nullable=True, comment='部门'),
    sa.Column('institution', sa.String(length=500), nullable=True, comment='机构名称'),
    sa.Column('city', sa.String(length=100), nullable=True, comment='城市'),
    sa.Column('state', sa.String(length=100), nullable=True, comment='州/省'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国家'),
    sa.Column('email', sa.String(length=200), nullable=True, comment='联系邮箱'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliation_country'), 'affiliation', ['country'], unique=False)
    op.create_index(op.f('ix_affiliation_institution'), 'affiliation', ['institution'], unique=False)
    op.create_table('author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('last_name', sa.String(length=100), nullable=True, comment='姓'),
    sa.Column('fore_name', sa.String(length=100), nullable=True, comment='名'),
    sa.Column('initials', sa.String(length=20), nullable=True, comment='缩写'),
    sa.Column('collective_name', sa.String(length=500), nullable=True, comment='团体作者名称'),
    sa.Column('orcid', sa.String(length=20), nullable=True, comment='ORCID标识符'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_author_last_name'), 'author', ['last_name'], unique=False)
    op.create_index(op.f('ix_author_orcid'), 'author', ['orcid'], unique=True)
    op.create_table('chemical',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name_of_substance', sa.String(length=300), nullable=False, comment='化学物质名称'),
    sa.Column('registry_number', sa.String(length=50), nullable=True, comment='注册号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemical_registry_number'), 'chemical', ['registry_number'], unique=True)
    op.create_table('grant',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('grant_id', sa.String(length=100), nullable=True, comment='基金ID'),
    sa.Column('acronym', sa.String(length=50), nullable=True, comment='缩写'),
    sa.Column('agency', sa.String(length=300), nullable=True, comment='资助机构'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国家'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grant_id', 'agency', name='uq_grant_agency')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('title', sa.String(length=300), nullable=False, comment='期刊全称'),
    sa.Column('iso_abbreviation', sa.String(length=200), nullable=True, comment='ISO缩写'),
    sa.Column('issn', sa.String(length=20), nullable=True, comment='ISSN号（印刷版）'),
    sa.Column('issn_linking', sa.String(length=20), nullable=True, comment='ISSN Linking'),
    sa.Column('nlm_unique_id', sa.String(length=20), nullable=True, comment='NLM唯一ID'),
    sa.Column('medline_ta', sa.String(length=200), nullable=True, comment='MedlineTA'),
    sa.Column('country', sa.String(length=100), nullable=True, comment='国家'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_issn'), 'journal', ['issn'], unique=False)
    op.create_index(op.f('ix_journal_nlm_unique_id'), 'journal', ['nlm_unique_id'], unique=True)
    op.create_index(op.f('ix_journal_title'), 'journal', ['title'], unique=False)
    op.create_table('keyword',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('keyword', sa.String(length=500), nullable=False, comment='关键词'),
    sa.Column('keyword_type', sa.String(length=50), nullable=True, comment='关键词类型（Author/Other）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword', 'keyword_type', name='uq_keyword_type')
    )
    op.create_table('mesh_qualifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('qualifier_name', sa.String(length=300), nullable=False, comment='限定词名称'),
    sa.Column('qualifier_ui', sa.String(length=50), nullable=True, comment='限定词UI'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesh_qualifiers_qualifier_ui'), 'mesh_qualifiers', ['qualifier_ui'], unique=True)
    op.create_table('mesh_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('descriptor_name', sa.String(length=300), nullable=False, comment='描述符名称'),
    sa.Column('descriptor_ui', sa.String(length=50), nullable=True, comment='描述符UI'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mesh_terms_descriptor_ui'), 'mesh_terms', ['descriptor_ui'], unique=True)
    op.create_table('publication_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('type_name', sa.String(length=100), nullable=False, comment='类型名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('article',
    sa.Column('doi', sa.String(length=100), nullable=False, comment='DOI标识符，作为主键'),
    sa.Column('pmid', sa.String(length=20), nullable=True, comment='PubMed ID'),
    sa.Column('title', sa.Text(), nullable=False, comment='文献标题'),
    sa.Column('abstract', sa.Text(), nullable=True, comment='摘要'),
    sa.Column('pmc_id', sa.String(length=20), nullable=True, comment='PMC ID'),
    sa.Column('language', sa.String(length=10), nullable=True, comment='语言'),
    sa.Column('pagination', sa.String(length=50), nullable=True, comment='页码'),
    sa.Column('volume', sa.String(length=50), nullable=True, comment='卷号'),
    sa.Column('issue', sa.String(length=50), nullable=True, comment='期号'),
    sa.Column('article_date', sa.Date(), nullable=True, comment='文章发表日期'),
    sa.Column('journal_id', sa.Integer(), nullable=True, comment='关联期刊ID'),
    sa.Column('copyright_info', sa.Text(), nullable=True, comment='版权信息'),
    sa.Column('coi_statement', sa.Text(), nullable=True, comment='利益冲突声明'),
    sa.Column('last_crawled_at', sa.DateTime(timezone=True), nullable=True, comment='最后爬取时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('doi')
    )
    op.create_index(op.f('ix_article_article_date'), 'article', ['article_date'], unique=False)
    op.create_index(op.f('ix_article_journal_id'), 'article', ['journal_id'], unique=False)
    op.create_index(op.f('ix_article_last_crawled_at'), 'article', ['last_crawled_at'], unique=False)
    op.create_index(op.f('ix_article_pmc_id'), 'article', ['pmc_id'], unique=False)
    op.create_index(op.f('ix_article_pmid'), 'article', ['pmid'], unique=True)
    op.create_table('article_author_affiliations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('affiliation_id', sa.Integer(), nullable=False, comment='机构ID'),
    sa.Column('affiliation_order', sa.Integer(), nullable=False, comment='机构顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliation.id'], ),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_author_affiliations_affiliation_id'), 'article_author_affiliations', ['affiliation_id'], unique=False)
    op.create_index(op.f('ix_article_author_affiliations_article_doi'), 'article_author_affiliations', ['article_doi'], unique=False)
    op.create_index(op.f('ix_article_author_affiliations_author_id'), 'article_author_affiliations', ['author_id'], unique=False)
    op.create_table('article_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='作者ID'),
    sa.Column('author_order', sa.Integer(), nullable=False, comment='作者顺序'),
    sa.Column('is_corresponding', sa.Boolean(), nullable=False, comment='是否通讯作者'),
    sa.Column('equal_contrib', sa.Boolean(), nullable=False, comment='是否同等贡献'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_doi', 'author_id', 'author_order', name='uq_article_author_order')
    )
    op.create_index(op.f('ix_article_authors_article_doi'), 'article_authors', ['article_doi'], unique=False)
    op.create_index(op.f('ix_article_authors_author_id'), 'article_authors', ['author_id'], unique=False)
    op.create_table('article_chemicals',
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('chemical_id', sa.Integer(), nullable=False, comment='化学物质ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.PrimaryKeyConstraint('article_doi', 'chemical_id')
    )
    op.create_table('article_grants',
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('grant_id', sa.Integer(), nullable=False, comment='基金ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['grant_id'], ['grant.id'], ),
    sa.PrimaryKeyConstraint('article_doi', 'grant_id')
    )
    op.create_table('article_ids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('id_type', sa.String(length=50), nullable=False, comment='ID类型（pii/pmc/mid等）'),
    sa.Column('id_value', sa.String(length=100), nullable=False, comment='ID值'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_doi', 'id_type', name='uq_article_id_type')
    )
    op.create_index(op.f('ix_article_ids_article_doi'), 'article_ids', ['article_doi'], unique=False)
    op.create_table('article_keywords',
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('keyword_id', sa.Integer(), nullable=False, comment='关键词ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keyword.id'], ),
    sa.PrimaryKeyConstraint('article_doi', 'keyword_id')
    )
    op.create_table('article_mesh_terms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('mesh_term_id', sa.Integer(), nullable=False, comment='MeSH术语ID'),
    sa.Column('is_major_topic', sa.Boolean(), nullable=False, comment='是否主要主题'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['mesh_term_id'], ['mesh_terms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_mesh_terms_article_doi'), 'article_mesh_terms', ['article_doi'], unique=False)
    op.create_index(op.f('ix_article_mesh_terms_is_major_topic'), 'article_mesh_terms', ['is_major_topic'], unique=False)
    op.create_table('article_publication_types',
    sa.Column('article_doi', sa.String(length=100), nullable=False, comment='文献DOI'),
    sa.Column('publication_type_id', sa.Integer(), nullable=False, comment='文献类型ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['publication_type_id'], ['publication_types.id'], ),
    sa.PrimaryKeyConstraint('article_doi', 'publication_type_id')
    )
    op.create_table('article_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('citing_doi', sa.String(length=100), nullable=False, comment='引用文献DOI'),
    sa.Column('cited_doi', sa.String(length=100), nullable=True, comment='被引文献DOI'),
    sa.Column('cited_pmid', sa.String(length=20), nullable=True, comment='被引文献PMID'),
    sa.Column('reference_string', sa.Text(), nullable=True, comment='原始引用字符串'),
    sa.Column('reference_order', sa.Integer(), nullable=True, comment='引用顺序'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['cited_doi'], ['article.doi'], ),
    sa.ForeignKeyConstraint(['citing_doi'], ['article.doi'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_references_cited_doi'), 'article_references', ['cited_doi'], unique=False)
    op.create_index(op.f('ix_article_references_cited_pmid'), 'article_references', ['cited_pmid'], unique=False)
    op.create_index(op.f('ix_article_references_citing_doi'), 'article_references', ['citing_doi'], unique=False)
    op.create_table('article_mesh_qualifiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('article_mesh_id', sa.Integer(), nullable=False, comment='article_mesh_terms表的ID'),
    sa.Column('qualifier_id', sa.Integer(), nullable=False, comment='限定词ID'),
    sa.Column('is_major_topic', sa.Boolean(), nullable=False, comment='是否主要主题'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['article_mesh_id'], ['article_mesh_terms.id'], ),
    sa.ForeignKeyConstraint(['qualifier_id'], ['mesh_qualifiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_mesh_qualifiers')
    op.drop_index(op.f('ix_article_references_citing_doi'), table_name='article_references')
    op.drop_index(op.f('ix_article_references_cited_pmid'), table_name='article_references')
    op.drop_index(op.f('ix_article_references_cited_doi'), table_name='article_references')
    op.drop_table('article_references')
    op.drop_table('article_publication_types')
    op.drop_index(op.f('ix_article_mesh_terms_is_major_topic'), table_name='article_mesh_terms')
    op.drop_index(op.f('ix_article_mesh_terms_article_doi'), table_name='article_mesh_terms')
    op.drop_table('article_mesh_terms')
    op.drop_table('article_keywords')
    op.drop_index(op.f('ix_article_ids_article_doi'), table_name='article_ids')
    op.drop_table('article_ids')
    op.drop_table('article_grants')
    op.drop_table('article_chemicals')
    op.drop_index(op.f('ix_article_authors_author_id'), table_name='article_authors')
    op.drop_index(op.f('ix_article_authors_article_doi'), table_name='article_authors')
    op.drop_table('article_authors')
    op.drop_index(op.f('ix_article_author_affiliations_author_id'), table_name='article_author_affiliations')
    op.drop_index(op.f('ix_article_author_affiliations_article_doi'), table_name='article_author_affiliations')
    op.drop_index(op.f('ix_article_author_affiliations_affiliation_id'), table_name='article_author_affiliations')
    op.drop_table('article_author_affiliations')
    op.drop_index(op.f('ix_article_pmid'), table_name='article')
    op.drop_index(op.f('ix_article_pmc_id'), table_name='article')
    op.drop_index(op.f('ix_article_last_crawled_at'), table_name='article')
    op.drop_index(op.f('ix_article_journal_id'), table_name='article')
    op.drop_index(op.f('ix_article_article_date'), table_name='article')
    op.drop_table('article')
    op.drop_table('publication_types')
    op.drop_index(op.f('ix_mesh_terms_descriptor_ui'), table_name='mesh_terms')
    op.drop_table('mesh_terms')
    op.drop_index(op.f('ix_mesh_qualifiers_qualifier_ui'), table_name='mesh_qualifiers')
    op.drop_table('mesh_qualifiers')
    op.drop_table('keyword')
    op.drop_index(op.f('ix_journal_title'), table_name='journal')
    op.drop_index(op.f('ix_journal_nlm_unique_id'), table_name='journal')
    op.drop_index(op.f('ix_journal_issn'), table_name='journal')
    op.drop_table('journal')
    op.drop_table('grant')
    op.drop_index(op.f('ix_chemical_registry_number'), table_name='chemical')
    op.drop_table('chemical')
    op.drop_index(op.f('ix_author_orcid'), table_name='author')
    op.drop_index(op.f('ix_author_last_name'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_affiliation_institution'), table_name='affiliation')
    op.drop_index(op.f('ix_affiliation_country'), table_name='affiliation')
    op.drop_table('affiliation')
    # ### end Alembic commands ###
